chore: remove verify stage image in prod

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -197,16 +197,16 @@ jobs:
        - name: Checkout repository
          uses: actions/checkout@v3
 
-       - name: Verify Stage Image Exists
-         run: |
-           IMAGE="${{ env.REGISTRY }}:${{ env.IMAGE_TAG }}"
-           echo "Checking if $IMAGE exists..."
-           if docker manifest inspect "$IMAGE" >/dev/null 2>&1; then
-             echo "Image exists, ready to deploy."
-           else
-             echo "ERROR: Stage image not found!"
-             exit 1
-           fi
+#       - name: Verify Stage Image Exists
+#         run: |
+#           IMAGE="${{ env.REGISTRY }}:${{ env.IMAGE_TAG }}"
+#           echo "Checking if $IMAGE exists..."
+#           if docker manifest inspect "$IMAGE" >/dev/null 2>&1; then
+#             echo "Image exists, ready to deploy."
+#           else
+#             echo "ERROR: Stage image not found!"
+#             exit 1
+#           fi
        - name: Set up Kubeconfig
          run: |
            mkdir -p ~/.kube
