chore: change env and verify image in prod

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -197,16 +197,16 @@ jobs:
        - name: Checkout repository
          uses: actions/checkout@v3
 
-#       - name: Verify Stage Image Exists
-#         run: |
-#           IMAGE="${{ env.REGISTRY }}:${{ env.IMAGE_TAG }}"
-#           echo "Checking if $IMAGE exists..."
-#           if docker manifest inspect "$IMAGE" >/dev/null 2>&1; then
-#             echo "Image exists, ready to deploy."
-#           else
-#             echo "ERROR: Stage image not found!"
-#             exit 1
-#           fi
+       - name: Verify Staging Image Exists
+         run: |
+           IMAGE="${{ env.REGISTRY }}:${{ env.IMAGE_TAG }}"
+           echo "Checking $IMAGE..."
+           if docker manifest inspect "$IMAGE" >/dev/null 2>&1; then
+             echo "Image exists; proceeding."
+           else
+             echo "ERROR: $IMAGE not found in GHCR. Make sure this SHA is the one built/deployed to staging."
+             exit 1
+           fi
        - name: Set up Kubeconfig
          run: |
            mkdir -p ~/.kube
@@ -216,7 +216,7 @@ jobs:
        - name: Deploy to Production with Helm
          run: |
            IMAGE_TAG=${{ github.sha }}
-           echo "Deploying image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} to production"
+           echo "Deploying image: ${{ env.REGISTRY }}/${{ env.IMAGE_TAG }} to ${{ env.PROD_NS }}"
 
            helm upgrade --install my-app ./charts \
              --namespace ${{ env.PROD_NS}} \
